<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Click the following link: ]]>
    </line>
    <line>
      <![CDATA[<a target='_blank' href=Thu_Jun_17_20_35_59_CEST_2021.jpg>ScreenshotError</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target='_blank' href=Thu_Jun_17_20_35_59_CEST_2021.jpg><img src=Thu_Jun_17_20_35_59_CEST_2021.jpg height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[Click the following link: ]]>
    </line>
    <line>
      <![CDATA[<a target='_blank' href=Thu_Jun_17_20_35_59_CEST_2021.jpg>ScreenshotError</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target='_blank' href=Thu_Jun_17_20_35_59_CEST_2021.jpg><img src=Thu_Jun_17_20_35_59_CEST_2021.jpg height=200 width=200></img></a>]]>
    </line>
  </reporter-output>
  <suite name="Data Driven Framework" duration-ms="3005" started-at="2021-06-17T20:35:58 CEST" finished-at="2021-06-17T20:36:01 CEST">
    <groups>
    </groups>
    <test name="Bank Manager Login Test" duration-ms="1597" started-at="2021-06-17T20:35:58 CEST" finished-at="2021-06-17T20:35:59 CEST">
      <class name="pl.mwewerek.testcases.BankManagerLoginTest">
        <test-method status="FAIL" signature="bankManagerLoginTest()[pri:0, instance:pl.mwewerek.testcases.BankManagerLoginTest@428640fa]" name="bankManagerLoginTest" duration-ms="1173" started-at="2021-06-17T20:35:58 CEST" finished-at="2021-06-17T20:35:59 CEST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to login as a bank manager]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to login as a bank manager
at org.testng.Assert.fail(Assert.java:99)
at pl.mwewerek.testcases.BankManagerLoginTest.bankManagerLoginTest(BankManagerLoginTest.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click the following link: ]]>
            </line>
            <line>
              <![CDATA[<a target='_blank' href=Thu_Jun_17_20_35_59_CEST_2021.jpg>ScreenshotError</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target='_blank' href=Thu_Jun_17_20_35_59_CEST_2021.jpg><img src=Thu_Jun_17_20_35_59_CEST_2021.jpg height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- bankManagerLoginTest -->
      </class> <!-- pl.mwewerek.testcases.BankManagerLoginTest -->
    </test> <!-- Bank Manager Login Test -->
    <test name="Add Customer Test" duration-ms="1391" started-at="2021-06-17T20:35:59 CEST" finished-at="2021-06-17T20:36:01 CEST">
      <class name="pl.mwewerek.testcases.AddCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:pl.mwewerek.testcases.AddCustomerTest@7b36aa0c]" name="setUp" is-config="true" duration-ms="5239" started-at="2021-06-17T20:35:53 CEST" finished-at="2021-06-17T20:35:58 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="addCustomerTest(java.util.Hashtable)[pri:0, instance:pl.mwewerek.testcases.AddCustomerTest@7b36aa0c]" name="addCustomerTest" duration-ms="1041" started-at="2021-06-17T20:36:00 CEST" data-provider="dataProvider" finished-at="2021-06-17T20:36:01 CEST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{postCode=01-111, lastName=Wewerek, firstName=Michal, alertText=Customer added successfully with customer id}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Add Customer Test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Add Customer Test failed
at org.testng.Assert.fail(Assert.java:99)
at pl.mwewerek.testcases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click the following link: ]]>
            </line>
            <line>
              <![CDATA[<a target='_blank' href=Thu_Jun_17_20_35_59_CEST_2021.jpg>ScreenshotError</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target='_blank' href=Thu_Jun_17_20_35_59_CEST_2021.jpg><img src=Thu_Jun_17_20_35_59_CEST_2021.jpg height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:pl.mwewerek.testcases.AddCustomerTest@7b36aa0c]" name="tearDown" is-config="true" duration-ms="811" started-at="2021-06-17T20:36:01 CEST" finished-at="2021-06-17T20:36:02 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- pl.mwewerek.testcases.AddCustomerTest -->
    </test> <!-- Add Customer Test -->
  </suite> <!-- Data Driven Framework -->
</testng-results>
